export const englishFalsePluralWords: Array<string> = [
	"aegis",
	"alias",
	"analysis",
	"apparatus",
	"asparagus",
	"bias",
	"billiards",
	"bitters",
	"chassis",
	"claustrophobia",
	"corps",
	"cosmos",
	"crisis",
	"diabetes",
	"diagnosis",
	"diphtheria",
	"economics",
	"ethics",
	"gas",
	"genetics",
	"headquarters",
	"herpes",
	"innings",
	"lens",
	"mathematics",
	"measles",
	"mechanics",
	"mumps",
	"news",
	"nexus",
	"ophthalmoscope",
	"physics",
	"polis",
	"politics",
	"premises",
	"rabies",
	"rickets",
	"rhinoceros",
	"scissors",
	"series",
	"species",
	"terminus",
	"this",
	"tiddlywinks",
	"typhus",
];

// Mapping of singular forms to their irregular plural forms
export const englishIrregularPlurals: Record<string, string> = {
	addendum: "addenda",
	aircraft: "aircraft",
	alumna: "alumnae",
	alumnus: "alumni",
	analysis: "analyses",
	antithesis: "antitheses",
	apex: "apices",
	appendix: "appendices",
	axis: "axes",
	bacillus: "bacilli",
	bacterium: "bacteria",
	basis: "bases",
	beau: "beaux",
	bison: "bison",
	bureau: "bureaux",
	cactus: "cacti",
	calf: "calves",
	cervix: "cervices",
	child: "children",
	codex: "codices",
	concerto: "concerti",
	corpus: "corpora",
	crisis: "crises",
	criterion: "criteria",
	curriculum: "curricula",
	datum: "data",
	deer: "deer",
	diagnosis: "diagnoses",
	die: "dice",
	dogma: "dogmata",
	dwarf: "dwarves",
	elf: "elves",
	ellipsis: "ellipses",
	erratum: "errata",
	fish: "fish",
	focus: "foci",
	foot: "feet",
	formula: "formulae",
	fungus: "fungi",
	genus: "genera",
	goose: "geese",
	graffito: "graffiti",
	half: "halves",
	hoof: "hooves",
	hypothesis: "hypotheses",
	index: "indices",
	knife: "knives",
	larva: "larvae",
	leaf: "leaves",
	lemma: "lemmata",
	life: "lives",
	loaf: "loaves",
	louse: "lice",
	man: "men",
	matrix: "matrices",
	medium: "media",
	memorandum: "memoranda",
	minutia: "minutiae",
	moose: "moose",
	mouse: "mice",
	nebula: "nebulae",
	nucleus: "nuclei",
	oasis: "oases",
	octopus: "octopi",
	ovum: "ova",
	ox: "oxen",
	parenthesis: "parentheses",
	person: "people",
	phenomenon: "phenomena",
	phylum: "phyla",
	prognosis: "prognoses",
	quiz: "quizzes",
	radius: "radii",
	scarf: "scarves",
	self: "selves",
	series: "series",
	sheep: "sheep",
	shelf: "shelves",
	spacecraft: "spacecraft",
	species: "species",
	stimulus: "stimuli",
	stratum: "strata",
	syllabus: "syllabi",
	symposium: "symposia",
	synopsis: "synopses",
	thesis: "theses",
	thief: "thieves",
	tooth: "teeth",
	vertex: "vertices",
	vortex: "vortices",
	wife: "wives",
	wolf: "wolves",
	woman: "women",
};

// Mapping of irregular plural forms to their singular forms
export const englishIrregularSingulars: Record<string, string> = Object.fromEntries(Object.entries(englishIrregularPlurals).map(([singular, plural]: [string, string]) => [plural, singular]));

// English words that don't have distinct plural forms
export const englishUncountableWords: Array<string> = [
	"advice",
	"entertainment",
	"fun",
	"air",
	"mathematics",
	"salmon",
	"physics",
	"politics",
	"measles",
	"mumps",
	"diabetes",
	"software",
	"hardware",
	"firmware",
	"internet",
	"economics",
	"ethics",
	"alcohol",
	"art",
	"trout",
	"swine",
	"baggage",
	"blood",
	"butter",
	"cash",
	"chalk",
	"chaos",
	"cheese",
	"china",
	"clothing",
	"coal",
	"coffee",
	"commerce",
	"compassion",
	"cotton",
	"courage",
	"cream",
	"currency",
	"damage",
	"demographics",
	"dirt",
	"dust",
	"education",
	"electricity",
	"energy",
	"engineering",
	"equipment",
	"evidence",
	"fame",
	"feedback",
	"fiction",
	"fish",
	"flour",
	"food",
	"freedom",
	"fuel",
	"furniture",
	"garbage",
	"gold",
	"gossip",
	"grass",
	"gratitude",
	"grief",
	"ground",
	"guilt",
	"hair",
	"happiness",
	"hardware",
	"harm",
	"health",
	"heat",
	"help",
	"homework",
	"honey",
	"hospitality",
	"housework",
	"humor",
	"ice",
	"importance",
	"information",
	"intelligence",
	"jam",
	"jewelry",
	"joy",
	"justice",
	"knowledge",
	"laughter",
	"leather",
	"leisure",
	"lightning",
	"linguine",
	"literature",
	"love",
	"luck",
	"luggage",
	"machinery",
	"magic",
	"mail",
	"management",
	"meat",
	"milk",
	"money",
	"morale",
	"mud",
	"music",
	"news",
	"nitrogen",
	"nutrition",
	"oil",
	"oxygen",
	"pasta",
	"patience",
	"peace",
	"pepper",
	"poetry",
	"pollution",
	"poverty",
	"power",
	"produce",
	"progress",
	"psychology",
	"publicity",
	"punctuation",
	"quality",
	"quantity",
	"rain",
	"recreation",
	"research",
	"rice",
	"sadness",
	"safety",
	"salt",
	"sand",
	"seafood",
	"shopping",
	"silver",
	"sleep",
	"smoke",
	"snow",
	"soap",
	"software",
	"soup",
	"spaghetti",
	"speed",
	"steam",
	"steel",
	"sugar",
	"sunshine",
	"tea",
	"tennis",
	"thunder",
	"timber",
	"time",
	"traffic",
	"transportation",
	"travel",
	"trash",
	"trust",
	"understanding",
	"underwear",
	"unemployment",
	"usage",
	"vinegar",
	"violence",
	"vision",
	"water",
	"wealth",
	"weather",
	"wheat",
	"wildlife",
	"wine",
	"wisdom",
	"wood",
	"wool",
	"work",
	"yoga",
];
