import { Gender } from "../../domain/enum/gender.enum";
export const russianIrregularPlurals = {
    // Masculine exceptions
    'человек': { plural: 'люди', gender: Gender.Masculine },
    'ребёнок': { plural: 'дети', gender: Gender.Masculine },
    'друг': { plural: 'друзья', gender: Gender.Masculine },
    'брат': { plural: 'братья', gender: Gender.Masculine },
    'сын': { plural: 'сыновья', gender: Gender.Masculine },
    'муж': { plural: 'мужья', gender: Gender.Masculine },
    'стул': { plural: 'стулья', gender: Gender.Masculine },
    'лист': { plural: 'листья', gender: Gender.Masculine },
    'дерево': { plural: 'деревья', gender: Gender.Neuter },
    'цветок': { plural: 'цветы', gender: Gender.Masculine },
    'чудо': { plural: 'чудеса', gender: Gender.Neuter },
    'небо': { plural: 'небеса', gender: Gender.Neuter },
    'глаз': { plural: 'глаза', gender: Gender.Masculine },
    'ухо': { plural: 'уши', gender: Gender.Neuter },
    'дом': { plural: 'дома', gender: Gender.Masculine },
    'город': { plural: 'города', gender: Gender.Masculine },
    'поезд': { plural: 'поезда', gender: Gender.Masculine },
    'адрес': { plural: 'адреса', gender: Gender.Masculine },
    'паспорт': { plural: 'паспорта', gender: Gender.Masculine },
    'доктор': { plural: 'доктора', gender: Gender.Masculine },
    'профессор': { plural: 'профессора', gender: Gender.Masculine },
    'номер': { plural: 'номера', gender: Gender.Masculine },
    'вечер': { plural: 'вечера', gender: Gender.Masculine },
    'холод': { plural: 'холода', gender: Gender.Masculine },
    'берег': { plural: 'берега', gender: Gender.Masculine },
    'свитер': { plural: 'свитера', gender: Gender.Masculine },
    'тополь': { plural: 'тополя', gender: Gender.Masculine },
    'директор': { plural: 'директора', gender: Gender.Masculine },
    'инспектор': { plural: 'инспектора', gender: Gender.Masculine },
    'катер': { plural: 'катера', gender: Gender.Masculine },
    'соус': { plural: 'соусы', gender: Gender.Masculine },
    'крем': { plural: 'кремы', gender: Gender.Masculine },
    'торт': { plural: 'торты', gender: Gender.Masculine },
    'шарф': { plural: 'шарфы', gender: Gender.Masculine },
    'год': { plural: 'года', gender: Gender.Masculine },
    'снег': { plural: 'снега', gender: Gender.Masculine },
    'рукав': { plural: 'рукава', gender: Gender.Masculine },
    'голос': { plural: 'голоса', gender: Gender.Masculine },
    'край': { plural: 'края', gender: Gender.Masculine },
    'учитель': { plural: 'учителя', gender: Gender.Masculine },
    'якорь': { plural: 'якоря', gender: Gender.Masculine },
    'хлеб': { plural: 'хлеба', gender: Gender.Masculine },
    'остров': { plural: 'острова', gender: Gender.Masculine },
    'повар': { plural: 'повара', gender: Gender.Masculine },
    'ветер': { plural: 'ветра', gender: Gender.Masculine },
    'пояс': { plural: 'пояса', gender: Gender.Masculine },
    'сторож': { plural: 'сторожа', gender: Gender.Masculine },
    // Feminine exceptions
    'книга': { plural: 'книги', gender: Gender.Feminine },
    'сестра': { plural: 'сёстры', gender: Gender.Feminine },
    'рука': { plural: 'руки', gender: Gender.Feminine },
    'нога': { plural: 'ноги', gender: Gender.Feminine },
    'голова': { plural: 'головы', gender: Gender.Feminine },
    'щека': { plural: 'щёки', gender: Gender.Feminine },
    'свеча': { plural: 'свечи', gender: Gender.Feminine },
    'овца': { plural: 'овцы', gender: Gender.Feminine },
    'игра': { plural: 'игры', gender: Gender.Feminine },
    'доска': { plural: 'доски', gender: Gender.Feminine },
    'река': { plural: 'реки', gender: Gender.Feminine },
    'гора': { plural: 'горы', gender: Gender.Feminine },
    'звезда': { plural: 'звёзды', gender: Gender.Feminine },
    'страна': { plural: 'страны', gender: Gender.Feminine },
    'душа': { plural: 'души', gender: Gender.Feminine },
    'туча': { plural: 'тучи', gender: Gender.Feminine },
    'дача': { plural: 'дачи', gender: Gender.Feminine },
    'задача': { plural: 'задачи', gender: Gender.Feminine },
    'встреча': { plural: 'встречи', gender: Gender.Feminine },
    'роща': { plural: 'рощи', gender: Gender.Feminine },
    'дыра': { plural: 'дыры', gender: Gender.Feminine },
    'мера': { plural: 'меры', gender: Gender.Feminine },
    'игла': { plural: 'иглы', gender: Gender.Feminine },
    'пчела': { plural: 'пчёлы', gender: Gender.Feminine },
    'слеза': { plural: 'слёзы', gender: Gender.Feminine },
    'жена': { plural: 'жёны', gender: Gender.Feminine },
    'цена': { plural: 'цены', gender: Gender.Feminine },
    'стена': { plural: 'стены', gender: Gender.Feminine },
    'вода': { plural: 'воды', gender: Gender.Feminine },
    'еда': { plural: 'еды', gender: Gender.Feminine },
    'среда': { plural: 'среды', gender: Gender.Feminine },
    'беда': { plural: 'беды', gender: Gender.Feminine },
    'мечта': { plural: 'мечты', gender: Gender.Feminine },
    'дочь': { plural: 'дочери', gender: Gender.Feminine },
    'мать': { plural: 'матери', gender: Gender.Feminine },
    'любовь': { plural: 'любови', gender: Gender.Feminine },
    'церковь': { plural: 'церкви', gender: Gender.Feminine },
    'деревня': { plural: 'деревни', gender: Gender.Feminine },
    'песня': { plural: 'песни', gender: Gender.Feminine },
    'земля': { plural: 'земли', gender: Gender.Feminine },
    'неделя': { plural: 'недели', gender: Gender.Feminine },
    'башня': { plural: 'башни', gender: Gender.Feminine },
    'дыня': { plural: 'дыни', gender: Gender.Feminine },
    'тетя': { plural: 'тети', gender: Gender.Feminine },
    'пуля': { plural: 'пули', gender: Gender.Feminine },
    'гиря': { plural: 'гири', gender: Gender.Feminine },
    // Neuter exceptions
    'колено': { plural: 'колени', gender: Gender.Neuter },
    'тело': { plural: 'тела', gender: Gender.Neuter },
    'место': { plural: 'места', gender: Gender.Neuter },
    'время': { plural: 'времена', gender: Gender.Neuter },
    'имя': { plural: 'имена', gender: Gender.Neuter },
    'семя': { plural: 'семена', gender: Gender.Neuter },
    'стремя': { plural: 'стремена', gender: Gender.Neuter },
    'племя': { plural: 'племена', gender: Gender.Neuter },
    'знамя': { plural: 'знамёна', gender: Gender.Neuter },
    'пламя': { plural: 'пламена', gender: Gender.Neuter },
    'вымя': { plural: 'вымена', gender: Gender.Neuter },
    'темя': { plural: 'темена', gender: Gender.Neuter },
    'слово': { plural: 'слова', gender: Gender.Neuter },
    'дело': { plural: 'дела', gender: Gender.Neuter },
    'окно': { plural: 'окна', gender: Gender.Neuter },
    'яйцо': { plural: 'яйца', gender: Gender.Neuter },
    'яблоко': { plural: 'яблоки', gender: Gender.Neuter },
    'облако': { plural: 'облака', gender: Gender.Neuter },
    'плечо': { plural: 'плечи', gender: Gender.Neuter },
    'крыло': { plural: 'крылья', gender: Gender.Neuter },
    'перо': { plural: 'перья', gender: Gender.Neuter },
    'ребро': { plural: 'рёбра', gender: Gender.Neuter },
    'ведро': { plural: 'вёдра', gender: Gender.Neuter },
    'зерно': { plural: 'зёрна', gender: Gender.Neuter },
    'письмо': { plural: 'письма', gender: Gender.Neuter },
    'число': { plural: 'числа', gender: Gender.Neuter },
    'поле': { plural: 'поля', gender: Gender.Neuter },
    'море': { plural: 'моря', gender: Gender.Neuter },
    'горе': { plural: 'горя', gender: Gender.Neuter },
    'сердце': { plural: 'сердца', gender: Gender.Neuter },
    'лицо': { plural: 'лица', gender: Gender.Neuter },
    'блюдце': { plural: 'блюдца', gender: Gender.Neuter },
    'крыльцо': { plural: 'крыльца', gender: Gender.Neuter },
    'зеркало': { plural: 'зеркала', gender: Gender.Neuter },
    'полотенце': { plural: 'полотенца', gender: Gender.Neuter },
    'правило': { plural: 'правила', gender: Gender.Neuter },
    'солнце': { plural: 'солнца', gender: Gender.Neuter },
};
// Convert irregular plurals to a mapping from plural to singular
export const russianIrregularSingulars = Object.entries(russianIrregularPlurals)
    .reduce((acc, [singular, entry]) => {
    acc[entry.plural] = singular;
    return acc;
}, {});
// Words that do not change form between singular and plural
export const russianUncountableWords = [
    // Pair words
    'ножницы',
    'брюки',
    'очки',
    'штаны',
    'шорты',
    'колготки',
    'трусы',
    'джинсы',
    'плавки',
    'перчатки',
    'варежки',
    'наушники',
    'гантели',
    'кусачки',
    'щипцы',
    'клещи',
    'тиски',
    'весы',
    'качели',
    'санки',
    'грабли',
    'коньки',
    'лыжи',
    'сани',
    'носилки',
    'тапки',
    'туфли',
    'ботинки',
    'кроссовки',
    'башмаки',
    'чулки',
    'носки',
    // Abstract concepts
    'деньги',
    'финансы',
    'средства',
    'хлопья',
    'макароны',
    'спагетти',
    'консервы',
    'дрожжи',
    'дрова',
    'бусы',
    'чётки',
    'кудри',
    'бигуди',
    'духи',
    'сливки',
    'всходы',
    'сумерки',
    'припасы',
    'каникулы',
    'выходные',
    'осадки',
    'заморозки',
    'данные',
    'координаты',
    'сведения',
    'экспонаты',
    'мемуары',
    'хроники',
    'анналы',
    // Subjects and disciplines
    'переговоры',
    'выборы',
    'хлопоты',
    'проводы',
    'дебаты',
    'прения',
    'аплодисменты',
    'роды',
    'похороны',
    'смотрины',
    'крестины',
    'именины',
    'поиски',
    'скачки',
    'бега',
    'гонки',
    'прятки',
    'салки',
    'горелки',
    'танцы',
    'карты',
    'шахматы',
    'шашки',
    'нарды',
    // Time
    'сутки',
    'будни',
    'выходные',
    // Materials and substances
    'чернила',
    'чаи',
    'меха',
    'всходы',
    'сливки',
    'сласти',
    'мюсли',
    'щи',
    'чипсы',
    'хлопья',
    'духи',
    'белила',
    'румяна',
    'тени',
    // Geographical features
    'ворота',
    'задворки',
    'мостки',
    'побережье',
    'окрестности',
    'джунгли',
    'дебри',
    'субтропики',
    'тропики',
    'Альпы',
    'Анды',
    'Карпаты',
    'Дарданеллы',
    'Афины',
    'Нидерланды',
    'Балканы',
    'Филиппины',
    'Кордильеры',
    'Сейшелы'
];
